[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "1.15.2"
solana-client = "1.15.2"
solana-program = "1.15.2"
sha2 = "0.10.5"
borsh = "1.5"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }